In [1]:
import sys
sys.path.append("../")
import warnings
warnings.filterwarnings('ignore')
from utils.utils_jupyter_notebook import predict_ec_and_scores_from_sequence,print_color_text
import numpy as np

In [2]:
sequence = "MWRLRRAAVACEVCQSLVKHSSGIKGSLPLQKLHLVSRSIYHSHHPTLKLQRPQLRTSFQQFSSLTNLPLRKLKFSPIKYGYQPRRNFWPARLATRLLKLRYLILGSAVGGGYTAKKTFDQWKDMIPDLSEYKWIVPDIVWEIDEYIDFEKIRKALPSSEDLVKLAPDFDKIVESLSLLKDFFTSGSPEETAFRATDRGSESDKHFRKVSDKEKIDQLQEELLHTQLKYQRILERLEKENKELRKLVLQKDDKGIHHRKLKKSLIDMYSEVLDVLSDYDASYNTQDHLPRVVVVGDQSAGKTSVLEMIAQARIFPRGSGEMMTRSPVKVTLSEGPHHVALFKDSSREFDLTKEEDLAALRHEIELRMRKNVKEGCTVSPETISLNVKGPGLQRMVLVDLPGVINTVTSGMAPDTKETIFSISKAYMQNPNAIILCIQDGSVDAERSIVTDLVSQMDPHGRRTIFVLTKVDLAEKNVASPSRIQQIIEGKLFPMKALGYFAVVTGKGNSSESIEAIREYEEEFFQNSKLLKTSMLKAHQVTTRNLSLAVSDCFWKMVRESVEQQADSFKATRFNLETEWKNNYPRLRELDRNELFEKAKNEILDEVISLSQVTPKHWEEILQQSLWERVSTHVIENIYLPAAQTMNSGTFNTTVDIKLKQWTDKQLPNKAVEVAWETLQEEFSRFMTEPKGKEHDDIFDKLKEAVKEESIKRHKWNDFAEDSLRVIQHNALEDRSISDKQQWDAAIYFMEEALQARLKDTENAIENMVGPDWKKRWLYWKNRTQEQCVHNETKNELEKMLKCNEEHPAYLASDEITTVRKNLESRGVEVDPSLIKDTWHQVYRRHFLKTALNHCNLCRRGFYYYQRHFVDSELECNDVVLFWRIQRMLAITANTLRQQLTNTEVRRLEKNVKEVLEDFAEDGEKKIKLLTGKRVQLAEDLKKVREIQEKLDAFIEALHQEK"
ec_class, intensite_color,probability_of_ec = predict_ec_and_scores_from_sequence(sequence)

Shape attentions_map : (480, 961, 961)
attentions_map : [[0.03932463 0.000748   0.00055946 ... 0.00151407 0.00146353 0.00194881]
 [0.00143358 0.00133658 0.00121485 ... 0.00118144 0.00117052 0.00147539]
 [0.00151325 0.00077107 0.0008791  ... 0.0012186  0.00110771 0.00148912]
 ...
 [0.00091194 0.00141747 0.0013795  ... 0.0011064  0.00097883 0.00133107]
 [0.00083244 0.00139912 0.00132717 ... 0.00109838 0.00098299 0.00131488]
 [0.00068778 0.00114007 0.00102828 ... 0.00101667 0.0009656  0.0012496 ]]
attentions map sum per dim 0 : [1.1702588  1.1030128  0.9443126  0.60492086 0.47958073 0.5676962
 0.5752612  0.5597449  0.55486035 0.49230033 0.5823892  1.1017557
 0.7096711  0.4948279  1.0675682  0.73860943 0.546406   0.5013221
 0.4753639  0.8647891  0.85726994 0.55902237 0.5497248  0.52440304
 0.66361445 0.862556   0.5220317  0.54734516 0.5034406  0.7959644
 0.504474   0.7227216  0.9136657  0.5188153  0.9013043  0.5250476
 0.5247245  0.5705485  0.6349358  0.57344455 0.68343776 1.1622009
 0.928

Mean dim 1 and sum dim 2 and select map 0 0.99999994
Mean dim 2 and sum dim 1 and select map 0 0.9999999
Verif sum to L : [0.99999994 0.9999996  1.         0.9999996  1.0000002  0.9999998
 0.99999964 0.9999997  0.9999994  0.99999976 0.99999994 0.99999994
 0.99999964 1.         0.99999964 0.9999998  0.9999996  1.
 0.99999994 1.         0.99999994 1.0000001  0.99999976 0.9999998
 1.         1.         0.99999994 1.         0.9999999  1.
 1.         1.         1.         1.         0.9999999  1.0000001
 0.99999976 0.9999995  0.9999999  0.9999999  0.9999993  0.9999999
 0.9999999  0.99999976 1.         1.0000002  0.99999917 0.9999994
 1.0000002  0.9999999  0.9999999  1.0000007  0.99999976 0.99999946
 0.9999999  1.0000007  0.9999994  1.         1.0000005  0.9999992
 0.9999998  1.0000001  0.9999995  1.0000002  1.         1.0000002
 0.9999998  0.99999976 1.0000001  1.         0.9999999  1.0000004
 1.         0.9999994  0.9999995  1.         1.         1.0000004
 0.99999964 0.9999998  0.9999999

In [3]:
print("EC class:",ec_class)
print("Probability:",probability_of_ec)

EC class: 3.6.5.5
Probability: 0.99968374


In [4]:
print("List_res:",intensite_color)

List_res: [0.04083315 0.02753935 0.01738645 0.01513383 0.01491189 0.01900426
 0.0151785  0.01605707 0.0157879  0.02088429 0.02039836 0.01971969
 0.01677204 0.02805106 0.01807945 0.01666875 0.02623724 0.02242395
 0.02405054 0.02541028 0.01912655 0.01917106 0.02124728 0.01877688
 0.02089512 0.01750994 0.01715035 0.01853076 0.02182778 0.01819018
 0.01905343 0.02442036 0.02441566 0.02799228 0.01890305 0.02088255
 0.02067472 0.03688038 0.02520333 0.02192777 0.02254365 0.01940616
 0.01613461 0.0189663  0.01956578 0.01944308 0.01659354 0.02039727
 0.01983805 0.01976526 0.01838412 0.02311383 0.02420473 0.01940017
 0.02215464 0.02293236 0.01818993 0.01888052 0.02364487 0.07779766
 0.01793659 0.02414631 0.02638796 0.01745493 0.0193069  0.01699761
 0.01936087 0.02221661 0.02081607 0.01937414 0.03093137 0.02045105
 0.0204182  0.01835995 0.01872994 0.0184265  0.01788705 0.018678
 0.01690804 0.02125638 0.01716243 0.01961183 0.01700106 0.01593234
 0.01827022 0.02227945 0.0191665  0.02106278 0.0233838

In [5]:
print_color_text(sequence, intensite_color, method="first_percentile_colorize", composante="green")

 

0 MWRLRRAAVA CEVCQSLVKH SSGIKGSLPL QKLHLVSRSI YHSHHPTLKL QRPQLRTSFQ QFSSLTNLPL RKLKFSPIKY GYQPRRNFWP ARLATRLLKL 

1 RYLILGSAVG GGYTAKKTFD QWKDMIPDLS EYKWIVPDIV WEIDEYIDFE KIRKALPSSE DLVKLAPDFD KIVESLSLLK DFFTSGSPEE TAFRATDRGS 

2 ESDKHFRKVS DKEKIDQLQE ELLHTQLKYQ RILERLEKEN KELRKLVLQK DDKGIHHRKL KKSLIDMYSE VLDVLSDYDA SYNTQDHLPR VVVVGDQSAG 

3 KTSVLEMIAQ ARIFPRGSGE MMTRSPVKVT LSEGPHHVAL FKDSSREFDL TKEEDLAALR HEIELRMRKN VKEGCTVSPE TISLNVKGPG LQRMVLVDLP 

4 GVINTVTSGM APDTKETIFS ISKAYMQNPN AIILCIQDGS VDAERSIVTD LVSQMDPHGR RTIFVLTKVD LAEKNVASPS RIQQIIEGKL FPMKALGYFA 

5 VVTGKGNSSE SIEAIREYEE EFFQNSKLLK TSMLKAHQVT TRNLSLAVSD CFWKMVRESV EQQADSFKAT RFNLETEWKN NYPRLRELDR NELFEKAKNE 

6 ILDEVISLSQ VTPKHWEEIL QQSLWERVST HVIENIYLPA AQTMNSGTFN TTVDIKLKQW TDKQLPNKAV EVAWETLQEE FSRFMTEPKG KEHDDIFDKL 

7 KEAVKEESIK RHKWNDFAED SLRVIQHNAL EDRSISDKQQ WDAAIYFMEE ALQARLKDTE NAIENMVGPD WKKRWLYWKN RTQEQCVHNE TKNELEKMLK 

8 CNEEHPAYLA SDEITTVRKN LESRGVEVDP SLIKDTWHQV YRRHFLKTAL NHCNLCRRGF YYYQRHFVDS ELECND

In [6]:
top20_interpretability = np.flip(np.argsort(intensite_color))[:20] +1
print("Top20:",top20_interpretability)

Top20: [468 301 398 240 470 467 295  60 300 297 298 466 296 293 469 727 465 578
 268 434]


In [7]:
indice_disease = [8,80,95,102,290,300,310,357,377,382,396,439,445,449,545,551,571,590,728,781,785,932,939,229]

In [8]:
print(set(top20_interpretability).intersection(set(indice_disease)))

{300}


In [13]:
#Mutation pos 8 : A>S
sequence = "MWRLRRAAVACEVCQSLVKHSSGIKGSLPLQKLHLVSRSIYHSHHPTLKLQRPQLRTSFQQFSSLTNLPLRKLKFSPIKYGYQPRRNFWPARLATRLLKLRYLILGSAVGGGYTAKKTFDQWKDMIPDLSEYKWIVPDIVWEIDEYIDFEKIRKALPSSEDLVKLAPDFDKIVESLSLLKDFFTSGSPEETAFRATDRGSESDKHFRKVSDKEKIDQLQEELLHTQLKYQRILERLEKENKELRKLVLQKDDKGIHHRKLKKSLIDMYSEVLDVLSDYDASYNTQDHLPRVVVVGDQSAGKTSVLEMIAQARIFPRGSGEMMTRSPVKVTLSEGPHHVALFKDSSREFDLTKEEDLAALRHEIELRMRKNVKEGCTVSPETISLNVKGPGLQRMVLVDLPGVINTVTSGMAPDTKETIFSISKAYMQNPNAIILCIQDGSVDAERSIVTDLVSQMDPHGRRTIFVLTKVDLAEKNVASPSRIQQIIEGKLFPMKALGYFAVVTGKGNSSESIEAIREYEEEFFQNSKLLKTSMLKAHQVTTRNLSLAVSDCFWKMVRESVEQQADSFKATRFNLETEWKNNYPRLRELDRNELFEKAKNEILDEVISLSQVTPKHWEEILQQSLWERVSTHVIENIYLPAAQTMNSGTFNTTVDIKLKQWTDKQLPNKAVEVAWETLQEEFSRFMTEPKGKEHDDIFDKLKEAVKEESIKRHKWNDFAEDSLRVIQHNALEDRSISDKQQWDAAIYFMEEALQARLKDTENAIENMVGPDWKKRWLYWKNRTQEQCVHNETKNELEKMLKCNEEHPAYLASDEITTVRKNLESRGVEVDPSLIKDTWHQVYRRHFLKTALNHCNLCRRGFYYYQRHFVDSELECNDVVLFWRIQRMLAITANTLRQQLTNTEVRRLEKNVKEVLEDFAEDGEKKIKLLTGKRVQLAEDLKKVREIQEKLDAFIEALHQEK"
index =300-1
sequence = sequence[:index] + "E" + sequence[index + 1:]
ec_class, intensite_color,probability_of_ec = predict_ec_and_scores_from_sequence(sequence)
print("EC class:",ec_class)
print("Probability:",probability_of_ec)

Shape attentions_map : (480, 961, 961)
attentions_map : [[0.03932413 0.00074799 0.00055945 ... 0.00151405 0.00146351 0.00194878]
 [0.00143326 0.00133628 0.00121458 ... 0.00118118 0.00117026 0.00147506]
 [0.00151295 0.00077092 0.00087893 ... 0.00121837 0.0011075  0.00148883]
 ...
 [0.0009117  0.00141709 0.00137913 ... 0.0011061  0.00097857 0.00133072]
 [0.00083222 0.00139875 0.00132682 ... 0.00109809 0.00098273 0.00131453]
 [0.00068761 0.00113979 0.00102802 ... 0.00101642 0.00096536 0.00124929]]
attentions map sum per dim 0 : [1.1698773  1.1028341  0.9441338  0.6047815  0.47946995 0.56756645
 0.57511884 0.5596037  0.5547202  0.49219128 0.58224785 1.101534
 0.7095118  0.4947106  1.067361   0.7384519  0.54629594 0.50120556
 0.47525778 0.86458844 0.85707223 0.55890787 0.54961485 0.524288
 0.66345686 0.86237323 0.52193576 0.54724795 0.5033246  0.7958016
 0.5043646  0.7225836  0.91346943 0.51870346 0.9010982  0.5249193
 0.5246054  0.57043344 0.63477516 0.5733204  0.68327606 1.1619616
 0.9281

Mean dim 1 and sum dim 2 and select map 0 1.0
Mean dim 2 and sum dim 1 and select map 0 0.9999999
Verif sum to L : [1.         0.9999995  0.99999994 0.9999996  1.0000002  0.9999999
 0.99999976 0.99999964 0.99999934 0.99999964 1.         1.
 0.99999964 1.         0.99999964 0.9999998  0.9999995  1.
 1.         1.         0.9999999  1.         0.9999997  0.99999976
 1.         0.99999994 1.         0.99999994 0.99999994 1.
 0.99999994 1.         1.         1.         0.9999999  1.0000004
 0.9999997  0.9999998  0.99999964 0.9999999  0.9999991  1.
 1.         0.99999934 1.0000002  1.0000001  0.99999917 0.9999994
 1.         0.9999997  0.9999999  0.9999998  0.99999946 0.9999999
 0.99999976 1.0000001  0.99999946 1.         1.0000002  1.0000001
 0.9999998  1.0000004  0.9999997  1.         1.0000004  0.99999976
 1.         0.99999994 0.99999976 0.9999993  1.0000001  1.0000002
 0.99999964 1.         1.0000004  0.9999995  1.0000005  0.99999994
 0.99999964 1.0000005  1.0000001  1.         1.00000